### PR TITLE
docs: update readme.md in /docs

### LINKED ISSUE #47: 文档示例代码有错误
# Look Image

image

# Same as the document

image

Package version ： 2.2.2-preview.6

image

### PR DESCRIPTION
**Pull request by quachhengtony**
- update readme.md in /docs
- closes #47

### CODE REVIEW

**Review by weianweigan — APPROVED** [review]

**Comment by quachhengtony** [comment]
Are there any guidelines on how to contribute to this project? I would like to contribute more. Thank you.

**Comment by weianweigan** [comment]
> Are there any guidelines on how to contribute to this project? I would like to contribute more. Thank you.

@quachhengtony Thanks! The [Milvus documentation](https://github.com/milvus-io/milvus/blob/master/CONTRIBUTING.md) contains instructions on how to contribute code, but the C# SDK lacks this documentation now.

**Comment by quachhengtony** [comment]
Thanks! I'll check it out. I plan to start with the bulk insert API issue.

**Comment by weianweigan** [comment]
> Anyway, will this PR get merged?

Of course, Thanks for your contribution.

**Pull request merged**
