### PR TITLE
Add Cosine SimilarityMetricType

### PR DESCRIPTION
**Pull request by MarioMartinPlaza**
Add Cosine SimilarityMetricType

### CODE REVIEW

**Review by weianweigan — APPROVED** [review]

**Comment by weianweigan** [comment]
Thanks @MarioMartinPlaza . 

> # Cosine Metrics
> The Cosine Metrics is widely regarded as the standard method for measuring the distance between vectors, particularly in Large Language Models (LLMs). With the release of Milvus 2.3.0, cosine metrics are now natively supported. As a result, users no longer need to quantize vectors for IP (Inner Product) metrics.

**Comment by weianweigan** [comment]
[Milvus v2.3.0 release notes](https://github.com/milvus-io/milvus/releases/tag/v2.3.0)

**Review by roji — CHANGES_REQUESTED** [review]
Note that just adding the enum value isn't enough - support also needs to be added in the GetGrpcMetricType method. I think a test that shows this working would also be a good idea.

@weianweigan note that I've already done some work for 2.3 support in the 2.3 branch. I think it's probably a good idea to merge that branch into main, so that main represents the latest version. We should also plan to complete the 2.3 work and release a package soon.

Is this something you can work on?

**Comment by weianweigan** [comment]
@roji  Thank you for the reminder. Let me take a look at this branch, and perhaps I can continue working on the 2.3 branch after the Spring Festival holiday.

**Comment by lofcz** [comment]
Glad to hear the needle is about to move forward with 2.3 support!

**Comment by yhmo** [comment]
Hi @roji, I have sent an invitation to you with the repo write access, please confirm. Thank you so much for updating this repo!

**Comment by roji** [comment]
Thanks @yhmo, received and accepted the invitation!

**Comment by roji** [comment]
@MarioMartinPlaza I rebased your commit, added the necessary implementation and testing and submitted as #63.

Can you please comment on #53 so I can assign you for credit?

**Pull request closed without merging**
