### PR TITLE
Add markdown documentation

### PR DESCRIPTION
**Pull request by roji**

### CODE REVIEW

**Review by weianweigan — APPROVED** [review]

**Comment by weianweigan** [comment]
Great! Thanks for your work. I'm wondering how we should generate API documentation. Is DocFX feasible?

**Comment by roji** [comment]
This is up to @yhmo - I sent a question about that on Slack. docfx would indeed be ideal for just generating API docs from the source code, but if the goal is to get markdown files that will be rendered like the other language reference APIs (e.g. [Python](https://milvus.io/api-reference/pymilvus/v2.3.x/About.md)), that's probably not going to be possible, and a lot of manual work will be needed.

@yhmo I'll wait for your answer on this.

**Comment by yhmo** [comment]
The API Reference can be an MD file with some sections to categorize APIs. The sections are not required to be consistent with other SDKs. Just clear to users is ok. For example: Connections, Database, Collection, Partition, Index, Utility, etc.

**Comment by roji** [comment]
I've just pushed API reference docs which are basically copy-pasted from the comments already present in the code.

@weianweigan could you give this additional comment another quick review?

@yhmo I'm hoping we can get this up on the website as quickly as possible!

/cc @luisquintanilla

**Review by weianweigan — APPROVED** [review]

**Comment by weianweigan** [comment]
Great! We have the API document now. I notified @yhmo. Should we merge this PR first?

**Review by weianweigan — APPROVED** [review]

**Comment by roji** [comment]
I think so - let me know if you need anything else from me here.

**Comment by weianweigan** [comment]
> I think so - let me know if you need anything else from me here.

OK！Thanks!

**Pull request merged**
