### PR TITLE
migrate from weianweigan/milvus-sdk-csharp

### PR DESCRIPTION
**Pull request by weianweigan**
migrate from weianweigan/milvus-sdk-csharp because of this [discussion](https://github.com/milvus-io/milvus/discussions/18333)

### CODE REVIEW

**Comment by yhmo** [comment]
@weianweigan 

I have some questions about the pr:
- Look likes this tool provides some UI controls(model dialogs) to interact with milvus, is this a common way in csharp? As we know, others sdk(pymilvus/javasdk/gosdk) only provide pure API to interact with milvus. Could csharp sdk be same way?
- Some comments in the code contain Chinese words, we require use English to write comment so that users all over the world can understand
- The classes design is mainly follow the Java sdk. There is a class MilvusMultiServiceClient for failover management, it is optional in java sdk, I think no need to implement it in csharp sdk.

**Comment by weianweigan** [comment]
@yhmo 
Thanks for your help.
* It's not a common way to develop a c# library with a GUI project. Attu needs a docker environment so I created it to manage milvus connections in my windows laptop. It's a standalone project. I will move it to another repository.
* There are some chinese words in the UI project and most of comments are generated by IDE. It will disappear when i remove the ui  project.
* I write c# sdk based on java.There are some useless code now, i will remove MilvusMultiServiceClient first.

**Comment by yhmo** [comment]
> @yhmo Thanks for your help.
> 
> * It's not a common way to develop a c# library with a GUI project. Attu needs a docker environment so I created it to manage milvus connections in my windows laptop. It's a standalone project. I will move it to another repository.
> * There are some chinese words in the UI project and most of comments are generated by IDE. It will disappear when i remove the ui  project.
> * I write c# sdk based on java.There are some useless code now, i will remove MilvusMultiServiceClient first.

Ok, after you remove the GUI part and the MilvusMultiServiceClient class, please contact me.

**Comment by weianweigan** [comment]
> 

I removed them.You can check latest three commit above your last comment in this pr for more information.

**Comment by yhmo** [comment]
Automation bot not yet ready, I manually merge this pr.

**Pull request merged**
